name: 🐛 Bug Report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        Please provide as much detail as possible to help us understand and reproduce the issue.

  - type: dropdown
    id: module
    attributes:
      label: Affected Module
      description: Which module is experiencing the issue?
      options:
        - azure-firewall
        - azure-load-balancer
        - azure-private-dns
        - azure-storage
        - azure-vm
        - azure-vnet
        - azure-vwan
        - azure-vwan-dns
        - azure-vwan-hub
        - Multiple modules
        - Repository/CI
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened and what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure module with...
        2. Run 'terraform apply'
        3. See error...
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Terraform Configuration
      description: Please provide the relevant Terraform configuration
      render: hcl
      placeholder: |
        module "example" {
          source = "./azure-module"
          # your configuration here
        }
    validations:
      required: true

  - type: textarea
    id: error-output
    attributes:
      label: Error Output
      description: If applicable, provide the full error output
      render: text
      placeholder: Paste the complete error message here

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please provide details about your environment
      placeholder: |
        - Terraform Version: 
        - Azure Provider Version: 
        - Operating System: 
        - Azure Region: 
        - Module Version/Commit: 
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots if applicable.
