blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/nova-iris/terraform-azure-modules/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/nova-iris/terraform-azure-modules/security/advisories
    about: Report security vulnerabilities privately
