name: ✨ Feature Request
description: Suggest an idea for this project
title: "[FEATURE] "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: dropdown
    id: module
    attributes:
      label: Target Module
      description: Which module would this feature affect?
      options:
        - azure-firewall
        - azure-load-balancer
        - azure-private-dns
        - azure-storage
        - azure-vm
        - azure-vnet
        - azure-vwan
        - azure-vwan-dns
        - azure-vwan-hub
        - New module
        - Multiple modules
        - Repository/CI
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New resource support
        - New configuration option
        - New module
        - Documentation improvement
        - CI/CD enhancement
        - Performance improvement
        - Security enhancement
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Description
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered

  - type: textarea
    id: example-usage
    attributes:
      label: Example Usage
      description: If applicable, provide an example of how this feature would be used
      render: hcl
      placeholder: |
        module "example" {
          source = "./azure-module"
          
          # new feature configuration
          new_feature_enabled = true
          new_feature_config = {
            setting1 = "value1"
            setting2 = "value2"
          }
        }

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What benefits would this feature provide?
      placeholder: |
        - Improved security
        - Better performance
        - Easier configuration
        - etc.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I'm willing to submit a PR for this feature
        - label: I can help with testing
        - label: I can help with documentation

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or links about the feature request here.
